%{?!ros_distro:%global ros_distro lyrical}
%global pkg_name wuji_hand2_beta2_description
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-lyrical-wuji-hand2-beta2-description
Version:        2026.8.19
Release:        1%{?dist}
Summary:        ROS %{pkg_name} package

License:        MIT
URL:            https://wuji.tech
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
Robot model description package for Wuji Hand 2 (Beta 2) with URDF, MJCF, and
USD assets for simulation and ROS2 visualization. Beta 2 keeps the frozen Beta 1
coordinate contract and adds one tactile-sensor pad link per fingertip.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Requires:       %{name}-runtime = %{version}-%{release}

%description devel
Robot model description package for Wuji Hand 2 (Beta 2) with URDF, MJCF, and
USD assets for simulation and ROS2 visualization. Beta 2 keeps the frozen Beta 1
coordinate contract and adds one tactile-sensor pad link per fingertip.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
Robot model description package for Wuji Hand 2 (Beta 2) with URDF, MJCF, and
USD assets for simulation and ROS2 visualization. Beta 2 keeps the frozen Beta 1
coordinate contract and adds one tactile-sensor pad link per fingertip.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DAMENT_PREFIX_PATH="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Wed Aug 19 2026 Wuji Technology <support@wuji.tech> - 2026.8.19-1
- Autogenerated by Bloom
