<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>wuji_hand2_beta1_description</name>
  <version>2026.8.19</version>
  <description>Robot model description package for Wuji Hand 2 (Beta 1) with URDF, MJCF, and USD assets for simulation and ROS2 visualization.</description>

  <maintainer email="support@wuji.tech">Wuji Technology</maintainer>

  <license>MIT</license>

  <url type="website">https://wuji.tech</url>
  <url type="bugtracker">https://github.com/wuji-technology/wuji-description/issues</url>
  <url type="repository">https://github.com/wuji-technology/wuji-description</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <architecture_independent/>
  </export>
</package>
