asset_path: ../output/robots/hand2_beta2/urdf/right.urdf
usd_dir: ../output/robots/hand2_beta2/_work/usd_physics/right
usd_file_name: wujihand2_beta2
force_usd_conversion: true
make_instanceable: true
fix_base: true
root_link_name: r_wrist
link_density: 1
merge_fixed_joints: false
convert_mimic_joints_to_normal_joints: false
joint_drive:
  drive_type: force
  target_type: position
  gains:
    stiffness:
      r_(thumb_cmc_flex|index_finger_mcp_flex|middle_finger_mcp_flex|ring_finger_mcp_flex|pinky_mcp_flex): 2
      r_(thumb_cmc_abd|index_finger_mcp_abd|middle_finger_mcp_abd|ring_finger_mcp_abd|pinky_mcp_abd): 2
      r_(thumb_mcp|index_finger_pip|middle_finger_pip|ring_finger_pip|pinky_pip): 1
      r_(thumb_ip|index_finger_dip|middle_finger_dip|ring_finger_dip|pinky_dip): 0.8
    damping:
      r_(thumb_cmc_flex|index_finger_mcp_flex|middle_finger_mcp_flex|ring_finger_mcp_flex|pinky_mcp_flex): 0.05
      r_(thumb_cmc_abd|index_finger_mcp_abd|middle_finger_mcp_abd|ring_finger_mcp_abd|pinky_mcp_abd): 0.05
      r_(thumb_mcp|index_finger_pip|middle_finger_pip|ring_finger_pip|pinky_pip): 0.03
      r_(thumb_ip|index_finger_dip|middle_finger_dip|ring_finger_dip|pinky_dip): 0.03
collider_type: convex_hull
self_collision: true
replace_cylinders_with_capsules: false
collision_from_visuals: false
##
# Generated by UrdfConverter on 2026-07-27 at 17:03:55.
##
